### ISSUE TITLE
be/todo - 회원가입 (자체 가입)

### ISSUE THREAD

**Issue by 021Skyfall** [kimtjrgus/salog#1]
## 설명
버텀-업으로 진행할 예정

## 할일
1. [x] : service 객체에 비지니스 로직 추가
2. [x] : 필요 시 repository 구현체 추가
3. [x] : mapping 작업
4. [x] : controller 통신 구현

## 특이사항
이메일 샌더와 Oauth2는 별도 이슈로 생성
이메일 샌더, Oauth2 제외 구현 완료시 이 이슈에 회원 관련 pr 링크할 것임(비밀번호 변경 별도)
존재하는 이메일인지 체크하는 함수 구현
로그인 제외 - 별도 이슈
