### ISSUE TITLE
be/todo - 가계부 : 지출 기본구조 구성

### ISSUE THREAD

**Issue by kimtjrgus** [kimtjrgus/salog#109]
## 설명
가계부 ledger/outgo 패키징 및 기본구조 구현

## 할일
1. [x] : outgo Entity, Mapper, Repository 셋팅
2. [x] : Service 기본 구조 구성
3. [x] : Controller 기본 구조 구성
4. [x] : 테스트
