### ISSUE TITLE
be/todo - 가계부 태그

### ISSUE THREAD

**Issue by 021Skyfall** [kimtjrgus/salog#127]
## 설명
가계부 태그 기본 틀 작성
일기 태그와 분리할 것
기본적인 것만 작성 후 푸쉬

## 할일
1. [x] : 일기 태그와 패키지, 네임 분리
2. [x] : 기본 구조 작성
3. [x] : controller
4. [x] : dto
5. [x] : entity (조인테이블 포함)
6. [x] : repository (조인테이블 포함)
7. [x] : service

## 특이사항
따로 조회될 필요 없이 수입, 지출 저장 시에 저장되어 같이 조회만 되면 됨

기본구조는 작성 끝남
상세한 것은 회의 후 진행

완성
