### ISSUE TITLE
fe/todo - 대시보드 기능

### ISSUE THREAD

**Issue by YujunSun0** [kimtjrgus/salog#131]
## 설명
가계부 대시보드 페이지 기능 구현

## 할일
1. [x] : 예산 막대그래프로 표현하기
2. [x] : 캘린더에 작성된 가계부를 토대로 지출, 수입 합계 표시
3. [x] : 캘린더에서 가계부 작성 모달, 타일 클릭 시 해당 일에 작성된 가계부 모달 기능
