### ISSUE TITLE
be/todo - 영수증 인식/ 자동작성

### ISSUE THREAD

**Issue by 021Skyfall** [kimtjrgus/Salog#23]
## 설명
Naver Clova OCR API를  이용한 영수증 인식 기능

클라이언트에서 이미지 url을 받아온 것을 based64 로 가공하여 clova ocr api 에 요청을 보내고,
응답받은 데이터를 가공하여 클라이언트에 응답해줄 것임. 
(영수증은 민감한 정보라서 서버에서 처리하는 것이 좋다고 생각함. )

## 할일
1. [x] : api문서 갱신
2. [x] : outgoService 에 관련 메서드 작성
3. [x] : outgoController 작성
4. [x] : naverClovaApi 를 핸들링 하기 위한 클래스 생성
5. [x] : api 관련하여 필요한 메서드 작성 
6. [x] : -> 오류 수정 

## 특이사항
- ocrDto를 따로 생성하고 ocrDto로 받은것을 outgoDto에 옮겨담아줄 것
왜? outgo와 ocr 클래스간의 결합도를 낮추기 위함.

- 결제수단 payment 에 대한 정보는 추후
- 이미지 확장자에 대한 핸들링은 추후 -> 현재는 확장자를 jpg로 변환시켜 jpg만 들어가게끔 설계

## 참고자료
- Spring서버에서 api호출하는 방법 https://thalals.tistory.com/266  
- 이미지 url -> base64 인코딩 https://developer-c.tistory.com/50

**Comment by kimtjrgus** [comment]
물어볼 것 : 이미지 기존정보가 무엇인지 무엇으로 전달가능한지 너무 길면 안되서 url로 전달하는 것이엇나?
