### ISSUE TITLE
fe/todo : 설정 페이지

### ISSUE THREAD

**Issue by YujunSun0** [kimtjrgus/Salog#249]
## 설명
설정 페이지 목업 및 비밀번호 변경 & 회원 탈퇴 기능

## 할일
1. [x] : 설정 페이지 디자인 및 목업
2. [x] : 비밀번호 변경 & 회원 탈퇴 기능
3. [x] : 지출 & 수입 태그 커스텀 기능 고민해보기

## 특이사항
x
