### ISSUE TITLE
be/todo - 회원

### ISSUE THREAD

**Issue by 021Skyfall** [kimtjrgus/salog#57]
## 설명
회원 기능 구조 전반 (JWT 별개, 세부 기능 별개)

## 할일
1. [x] : 회원 엔티티 구현
2. [x] : 회원 리포지터리 구현
3. [x] : 회원 서비스 구현
4. [x] : 회원 컨트롤러 구현
5. [x] : 회원 DTO 구현
6. [x]  : 회원 매퍼 구현

1. [x] : Auditable 객체 구현

## 특이사항 (푸시 X)
1. application.yml 파일 생성
2. gradle 의존성으로 JPA, Validation, H2, Mapper, Gson, JWT, Spring Security 추가
