### ISSUE TITLE
fe/todo - 임시 서버 구축

### ISSUE THREAD

**Issue by YujunSun0** [kimtjrgus/salog#65]
## 설명
json-server-auth 를 이용한 임시 서버 구축

## 할일
1. [x] : json-server 구축
2. [x] : 필요한 데이터들 세팅
3. [x] : 로그인, 회원가입 기능 테스트
