### ISSUE TITLE
be/todo - 페이지 설정 관련 로직 추가

### ISSUE THREAD

**Issue by kimtjrgus** [kimtjrgus/salog#71]
## 설명
Page 설정 관련 로직 추가
페이징에 관한 글로벌 클래스를 생성함.

## 할일
1. [x] : dto패키지 추가 
2. [x] : PageInfo 클래스 추가
3. [x] : MultiResponseDto 클래스 추가
4. [x] : SingleReponseDto 클래스 추가
