### ISSUE TITLE
fe/todo - 일기 작성 기능

### ISSUE THREAD

**Issue by YujunSun0** [kimtjrgus/salog#76]
## 설명
에디터를 이용한 일기 작성 기능구현 및 가계부 연동

## 할일
1. [x] : 텍스트 에디터를 이용하여 글씨체, 이미지 등.. 커스텀 가능한 에디터
2. [x] : 카테고리를 입력할 때, 쉼표/엔터를 누르면 추가 및 x 버튼을 누르면 삭제 기능
3. [ ] : 해당 일에 작성한 가계부의 지출/수입 기록 표시 기능

## 특이사항
가계부 관련 기능은 가계부 기능구현 후 진행
